<?php
$dil = array(
    "dilsecimi" => "Language Selection",
    "tr"=>"Turkish",
    "en"=>"English",
    "anasayfa" => "Home",
    "user"=>"User",
    "report"=>"Report",
    "EditProfile"=>"Edit Profile",
    "LogOut"=>"Log Out",
    "JOBFOLLOW"=>"JOB FOLLOW",
    "add"=>"ADD",
    "info"=>"Showing _START_ to _END_ of _TOTAL_ entries",
    "infoEmpty"=>"There are no records to show",
    "loadingRecords"=>"Loading recordings",
    "lengthMenu"=> "Show _MENU_ entries",
    "zeroRecords"=>"No matching records found",
    "search"=>"Search",
    "infoFiltered"=>" (filtered from _MAX_ total entries)",
    "first"=>"First",
    "previous"=>"Previous",
    "next"=>"Next",
    "last"=>"Last",
    "ViewSubRecord"=>"View Sub Record",
    "type"=>"REGISTRATION TYPE",
    "kayitno"=>"REGISTRATION NUMBER",
    "bildirimt"=>"NOTIFICATION DATE",
    "kayitacan"=>"OPENING REGISTRATION",
    "konu"=>"SUBJECT",
    "sorumlu"=>"RESPONSIBLE",
    "planlananbt"=>"PLANNED FINISH DATE",
    "tamamlanmat"=>"COMPLETION DATE",
    "status"=>"STATUS",
    "note"=>"NOTE",
    "operation"=>"OPERATİON",
);
?>
