<?php
$dil = array(
    "dilsecimi" => "Dil Seçiniz",
    "tr"=>"Türkçe",
    "en"=>"İngilizce",
    "anasayfa" => "Anasayfa",
    "user"=>"Kullanıcı",
    "report"=>"Rapor",
    "EditProfile"=>"Profilini Düzenle",
    "LogOut"=>"Çıkış Yap",
    "JOBFOLLOW"=>"İŞ TAKİP",
    "add"=>"EKLE",
    "info"=>"_TOTAL_ kayıttan _START_ - _END_ kayıt gösteriliyor",
    "infoEmpty"=>"Gösterilecek hiç kayıt yok",
    "loadingRecords"=>"Kayıtlar yükleniyor",
    "lengthMenu"=>"Sayfada _MENU_ kayıt göster",
    "zeroRecords"=>"Tablo Boş",
    "search"=>"Arama",
    "infoFiltered"=>"(toplam _MAX_ kayıttan filtrelenenler)",
    "first"=>"İlk",
    "previous"=>"Önceki",
    "next"=>"Sonraki",
    "last"=>"Son",
    "ViewSubRecord"=>"Alt Kayıt Görüntüle",
    "type"=>"KAYIT TÜRÜ",
    "kayitno"=>"KAYIT NO",
    "bildirimt"=>"BİLDİRİM TARİHİ",
    "kayitacan"=>"KAYIT AÇAN",
    "konu"=>"KONU",
    "sorumlu"=>"SORUMLU",
    "planlananbt"=>"PLANLANAN BİTİŞ TARİHİ",
    "tamamlanmat"=>"TAMAMLANMA TARİHİ",
    "status"=>"DURUM",
    "note"=>"NOT",
    "operation"=>"İŞLEM",
);
?>
